
import 'package:sweetmanager/ResourceManagement/models/report.dart';


final List<Report> reports = [
  Report(
    id: 1,
    typesReportsId: 2,
    adminsId: 1,
    workersId: 101,
    fileUrl: 'Scarcity of Resources',
    title: 'Water Supply Shortage',
    description: 'The water supply in the west wing has been consistently low, causing issues for guests.',
  ),
  Report(
    id: 2,
    typesReportsId: 1,
    adminsId: 2,
    workersId: 102,
    fileUrl: 'Maintenance',
    title: 'Broken Elevator in the Lobby',
    description: 'The elevator located in the lobby has been malfunctioning and needs immediate repair.',
  ),
  Report(
    id: 3,
    typesReportsId: 3,
    adminsId: 1,
    workersId: 103,
    fileUrl: 'Security',
    title: 'Suspicious Activity Near the Pool',
    description: 'Several guests reported unusual behavior around the pool area late at night.',
  ),
  Report(
    id: 4,
    typesReportsId: 2,
    adminsId: 1,
    workersId: 104,
    fileUrl: 'Scarcity of Resources',
    title: 'Low Stock of Guest Amenities',
    description: 'We are running low on essential guest amenities, including towels and toiletries.',
  ),
  Report(
    id: 5,
    typesReportsId: 1,
    adminsId: 2,
    workersId: 105,
    fileUrl: 'Maintenance',
    title: 'Air Conditioning Unit Malfunction',
    description: 'The air conditioning unit in room 304 is not cooling properly and requires maintenance.',
  ),
  Report(
    id: 6,
    typesReportsId: 3,
    adminsId: 3,
    workersId: 106,
    fileUrl: 'Security',
    title: 'Unattended Baggage in the Lobby',
    description: 'An unattended piece of baggage has been left in the lobby for over 30 minutes.',
  ),
  Report(
    id: 7,
    typesReportsId: 1,
    adminsId: 2,
    workersId: 107,
    fileUrl: 'Maintenance',
    title: 'Insufficient Lighting in Parking Area',
    description: 'The lighting in the parking area has been dim for the past few days, creating a potential hazard.',
  ),
  Report(
    id: 8,
    typesReportsId: 1,
    adminsId: 1,
    workersId: 108,
    fileUrl: 'Maintenance',
    title: 'Broken Handrail in Staircase',
    description: 'The handrail on the second-floor staircase is loose and needs to be repaired immediately.',
  ),
  Report(
    id: 9,
    typesReportsId: 3,
    adminsId: 3,
    workersId: 109,
    fileUrl: 'Security',
    title: 'Unauthorized Access in Staff Area',
    description: 'There was an incident of unauthorized access to the staff area by a non-employee.',
  ),
  Report(
    id: 10,
    typesReportsId: 3,
    adminsId: 1,
    workersId: 110,
    fileUrl: 'Security',
    title: 'Vandalism in the Guest Restroom',
    description: 'There has been recent vandalism in the guest restroom near the conference area.',
  ),
];
