// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios; // Devuelve la configuración para iOS
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTGEj8JZrWvn62ZtofnaGr-LluqliNXMc',
    appId: '1:180154492305:web:b156d317f56c1d4f34a630',
    messagingSenderId: '180154492305',
    projectId: 'sweet-solutions',
    authDomain: 'sweet-solutions.firebaseapp.com',
    storageBucket: 'sweet-solutions.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMvXGGWz59_ZcebY9Zzm4Z1_UcmyJVMn0',
    appId: '1:180154492305:android:3522d7bc118e3d6e34a630',
    messagingSenderId: '180154492305',
    projectId: 'sweet-solutions',
    storageBucket: 'sweet-solutions.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnDns4J0VpWEpIpckq2WmdVm2guy0h0K8', // API_KEY del plist
    appId: '1:180154492305:ios:3ca09082ded9f37934a630', // GOOGLE_APP_ID del plist
    messagingSenderId: '180154492305', // GCM_SENDER_ID del plist
    projectId: 'sweet-solutions', // PROJECT_ID del plist
    storageBucket: 'sweet-solutions.firebasestorage.app', // STORAGE_BUCKET del plist
    iosBundleId: 'Sweetmanager', // BUNDLE_ID del plist
  );
}
